env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo

task:
    name: ROMBuild
    timeout_in: 240m
    container:
      image: apon77/aosp:latest
      cpu: 16
      memory: 24G
    build_script:
      - ./setup.sh
